# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=22)),
                ('last_name', models.TextField(max_length=22)),
                ('street_number', models.TextField()),
                ('street_name', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
            ],
        ),
    ]
