# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-09 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_olduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Last_NM', models.TextField(max_length=122)),
                ('First_NM', models.TextField(max_length=122)),
                ('Street_NR', models.TextField()),
                ('Street_NM', models.TextField()),
                ('City', models.TextField()),
                ('State', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='OldUser',
        ),
    ]
